service: finapp-crawl

plugins:
  - serverless-offline

provider:
  name: aws
  profile: default
  stage: dev
  region: ap-northeast-1
  memorySize: 2048
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:ListBucket'
          Resource:
            - "*"
        - Effect: 'Allow'
          Action:
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource:
            - "*"
  environment:
    TZ: Asia/Tokyo

functions:
  stockprice-crawl-daily-1000-3000:
    image:
      name: "${env:ECR_ACCOUNT}.dkr.ecr.ap-northeast-1.amazonaws.com/finapp-lambda-crawl@${env:IMAGE_SHA_HASH}"
      command:
        - stockprice_crawl.crawl
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - schedule: cron(0 0 * * *)
    timeout: 1200
    environment:
      LAMBDA: 1
      START_CODE: 1000
      END_CODE: 3000
